PS1='${debian_chroot:+($debian_chroot)}\h:\w\$ '
umask 022

export LS_OPTIONS='--color=auto'
eval '$(dircolors)'
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias l='ls $LS_OPTIONS -lA'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

set -o vi

alias s='systemctl'
alias j='journalctl -xe'

[[ -f /opt/vultr/vultr_app.sh ]] && . /opt/vultr/vultr_app.sh
