PS1='${debian_chroot:+($debian_chroot)}\h:\w\$ '
umask 022

eval '$(dircolors)'
alias ls='ls --color=auto'
alias ll='ls --color=auto -l -l'
alias l='ls --color=auto -lA'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

set -o vi

alias s='systemctl'
alias j='journalctl -xe'

[[ -f /opt/vultr/vultr_app.sh ]] && . /opt/vultr/vultr_app.sh
